name: Build Snap

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'xibosignage/xibo-linux'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge