name: Deploy to SnapCraft

on:
  push:
    branches:
     - develop

jobs:
  build:
    name: Build and Deploy
    if: github.repository == 'xibosignage/xibo-linux'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        run: |
          docker build -f Dockerfile.snapcraft -t docker-snapcraft .
          echo ${{ secrets.SNAPCRAFT_TOKEN }} >> snapcraft.login
          docker build -f Dockerfile -t xibo-linux-snap .
          rm snapcraft.login

  in_fork:
    name: Skip in a fork
    runs-on: ubuntu-18.04
    if: github.repository != 'xibosignage/xibo-linux'
    steps:
      - name: Skip
        run: |
          echo 'Skipped while in a fork'
